import type { Metadata } from "next";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import CssBaseline from '@mui/material/CssBaseline';
import theme from '../theme/theme';
import "./globals.css";
import AppInitializer from "@/components/common/AppInitializer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            {/* CssBaseline kicksstart an elegant, consistent, and simple baseline to build upon. */}
            <CssBaseline />
            <AppInitializer>
              {children}
            </AppInitializer>

          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
